name: daily update
on:
  schedule:
    - cron: "29 9,18 * * *"
  workflow_dispatch:

jobs:
  test:
    name: update
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Install maltmill
        run: |
          brew install Songmu/tap/maltmill
      - name: update & pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make update-all
          git diff --exit-code --quiet && exit
          git diff --name-only | xargs -n 1 brew install --build-from-source
          git add *.rb
          git config --global user.email m.ikeda0901@gmail.com
          git config --global user.name mashiike
          git commit -m 'update to newer version'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3
        with:
          title: update to newer version
          reviewers: mashiike
