name: test
on: push

jobs:
  test:
    name: test
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin master
          git diff origin/master --name-only | fgrep .rb \
          | xargs -n 1 brew install --build-from-source
